name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore TaskManager.csproj

      - name: Build
        run: dotnet build TaskManager.csproj --no-restore

      - name: Test
        run: dotnet test TaskManager.csproj --no-build
